return {
  "mason-org/mason.nvim",
  opts = {
    ensure_installed = {
      "stylua",
      "shfmt",
      "google-java-format",
      "ast-grep",
      "biome",
      "clang-format",
      "clangd",
      "css-lsp",
      "docker-compose-language-service",
      "docker-language-server",
      "dockerfile-language-server",
      "emmet-ls",
      "gitui",
      "hyprls",
      "lemminx",
      "prettier",
      "ruff",
      "ty",
      "shellcheck",
      "stylelint",
      "tailwindcss-language-server",
      "tombi",
      "tree-sitter-cli",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
